USE `hotel`;
CREATE TABLE `fault_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fault_id` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(255) NOT NULL,
  `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_FAULT_COMMENT_FAULT_idx` (`fault_id`),
  CONSTRAINT `FK_FAULT_COMMENT_FAULT` FOREIGN KEY (`fault_id`) REFERENCES `fault` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
